modLoader="javafml"
loaderVersion="[43,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues"

[[mods]]
	modId="bettermineshafts"
	version="${file.jarVersion}"
	displayName="YUNG's Better Mineshafts"
	credits="Thanks so much to all my patrons!"
	authors="YUNGNICKYOUNG"
	description="The long-awaited and much-needed abandoned mineshaft overhaul!"
	logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge"

[[dependencies.bettermineshafts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"

[[dependencies.bettermineshafts]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"

[[dependencies.bettermineshafts]]
    modId="yungsapi"
    versionRange="[1.19.2-Forge-3.5.0,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"