modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge"
logoFile="BMLogo.png"

[[mods]]
	modId="${modId}"
	version="${version}"
	displayName="${modName}"
	credits="${modCredits}"
	authors="${modAuthor}"
	description="${modDescription}"

[[dependencies.bettermineshafts]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.bettermineshafts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"